version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: cat-backend:latest
    container_name: cat-backend
    ports:
      - "8080:8080"
    environment:
      THECATAPI_KEY: "live_JBT0Ah0Nt12iyl2IpjQVLDWjcLk0GQwf4zI9wBMfmfejKmcC31mOJp4yJz5TsOUP"

